services:
  audioconverter:
    image: ${DOCKER_REGISTRY-}audioconverter
    build:
      context: .
      dockerfile: AudioConverter/Dockerfile
  audioconverter-api:
      image: ${DOCKER_REGISTRY-}audioconverter-api
      build:
        context: .
        dockerfile: AudioRecorder.Api/Dockerfile
      ports:
        - "8080:80"
    
