services:
  audioconverter:
    image: ${DOCKER_REGISTRY-}audioconverter
    build:
      context: .
      dockerfile: AudioConverter/Dockerfile
  speechrecognitiontest:
    image: ${DOCKER_REGISTRY-}speechrecognitiontest
    build:
      context: .
      dockerfile: SpeechRecognition.Tests/Dockerfile
