version: "3.9"

services:
  postgres:
    build: ./postgres
    container_name: postgres-db
    ports:
      - "5436:5432"   # EXTERNO:5432 INTERNO
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: speechrecognition
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Painel Web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: always

volumes:
  postgres_data:
  rabbitmq_data:
